# Generated by Django 5.0 on 2024-01-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0002_alter_userdata_accent_color_alter_userdata_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='accent_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='avatar_decoration_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='banner_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='discriminator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
