# Generated by Django 5.0.1 on 2024-01-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0003_alter_userdata_accent_color_alter_userdata_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldUserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='nmid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
