# Generated by Django 5.0.1 on 2024-01-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0004_olduserdata_userdata_nmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='nmid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discordlogin.olduserdata'),
        ),
    ]
